### ISSUE TITLE
1v1 stats are just lines. Should be all bar graphs

### ISSUE THREAD

**Issue by Sciguymjm** [SaltieRL/DistributedReplays#107]
and pie charts probably

**Comment by reny** [comment]
PenguinTD here.

In https://github.com/SaltieRL/DistributedReplays/blob/master/webapp/src/Components/Shared/Charts/StatChart.tsx

add `const numberOfPlayers = this.props.basicStat.chartDataPoints.length` for type radar so it returns either ColoredPieChart or ColoredBarChart if numberOfPlayers is 2.

I don't have PC setup to do tests locally, so it's better for you guys to modify.
