### ISSUE TITLE
Material UI Core

### ISSUE THREAD

**Issue by Abbondanzo** [SaltieRL/DistributedReplays#169]
The newest version of the Material UI core package 3.2.0 and up. The current version of material UI pickers 1.0.0-rc.17 fails compilation. 

/../node_modules/material-ui-pickers/_shared/DateTextField.d.ts
(7,45): An interface may only extend a class or another interface.

The DateTextField interface extends a Type, which is illegal.

I'll submit a temporary PR to enforce Material UI core 3.1.2 but we should watch this package until it gets fixed:
https://github.com/dmtrKovalenko/material-ui-pickers

**Comment by Abbondanzo** [comment]
Can we reopen this to watch the package? I have a feeling the author might fix in the next week or so

**Comment by DarkAce65** [comment]
Reopening to watch the package for updates. See dmtrKovalenko/material-ui-pickers#676 and dmtrKovalenko/material-ui-pickers#678 for more info.

**Comment by DarkAce65** [comment]
Looks like this is ready to be fixed whenever you're ready @Abbondanzo.

**Comment by Abbondanzo** [comment]
Attempted to fix but am currently blocked by dmtrKovalenko/date-io#2. We can choose to use [release 1.0.1](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v1.0.1) but I would like to wait until the date-io abstraction has matured.
