### ISSUE TITLE
"plays with" shows bot name instead of playername

### ISSUE THREAD

**Issue by Bakkes** [SaltieRL/DistributedReplays#205]
Very low priority issue, but when looking at the "plays with" stat on my page (https://calculated.gg/players/76561198035894565/overview) it shows "Stinger". Clicking the name however does open the page for the right person.

Looking at my friends recent names through steam it doesn't look like he's ever used this name before so it's probably some other issue where it resolves a bot name (maybe from an unranked replay I uploaded somewhere earlier (with him in it)? Or some default list?). 

Anyway, nothing major, but just thought I'd report it.

**Comment by Sciguymjm** [comment]
https://imgur.com/CzB50ui

**Comment by Sciguymjm** [comment]
Thanks for reporting! But this looks like a Rocket League bug, interestingly enough.

**Comment by Bakkes** [comment]
Well I guess that it's actually my fault in that case 😅 . It's a result of me using the anonymizer option in BakkesMod which will change player names to bot names. Normally I don't have it enabled for party members but I guess in this case I did, and it just so happened that one replay is used when displaying the "played with". Didn't know the anonymizer would also change the playername in replays, neat!

Thanks for the quick response!

**Comment by Sciguymjm** [comment]
No problem! Closing this.
