### ISSUE TITLE
Stats explanation page math does not render

### ISSUE THREAD

**Issue by Abbondanzo** [SaltieRL/DistributedReplays#225]
When you navigate directly to the stats explanation page using the footer link, the math is not rendered correctly:
![ce8dba0aa4d616c63d5b54901fe80254](https://user-images.githubusercontent.com/10366495/50528741-1d1cc700-0abe-11e9-9c22-8347161e98a1.gif)

**Comment by LucasPickering** [comment]
I can take a crack at this one.

**Comment by Sciguymjm** [comment]
Supposedly fixed in #371 but in practice does not present a complete fix. Reproduce by going to Global Stats page and then use the sidebar/footer to go to explanations.

**Comment by Abbondanzo** [comment]
@Sciguymjm 

Works fine for me. Can you bust your cache? We should probably upgrade to React 16.5 to [add profiling support](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) and check that the lifecycle methods are properly triggering.

**Comment by Sciguymjm** [comment]
> @Sciguymjm
> 
> Works fine for me. Can you bust your cache? We should probably upgrade to React 16.5 to [add profiling support](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) and check that the lifecycle methods are properly triggering.

Busted my cache and it still did not work. Firefox, Mac Mojave.

**Comment by Sciguymjm** [comment]
<img width="868" alt="Screen Shot 2019-10-14 at 4 52 31 PM" src="https://user-images.githubusercontent.com/1396015/66790091-37842d80-eea3-11e9-8f80-7de61ad7415d.png">

**Comment by dtracers** [comment]
It works for me in chrome on Mac

**Comment by Sciguymjm** [comment]
It looks like the CDN is having issues as I type this (returning 425 status `No Reason Phrase`). I will verify at a later time.

**Comment by Abbondanzo** [comment]
Seems to be working as expected, going to close this one. Feel free to reopen if you see issues again
