### ISSUE TITLE
Camera transition speed stored as wrong datatype.

### ISSUE THREAD

**Issue by Bakkes** [SaltieRL/DistributedReplays#262]
I recently wrote a script which pulls the camera settings from pro players so players can directly apply them in-game, but I've got reports that the transition speed is wrong. We've verified that transition speed is indeed stored as a float in the replay, and Rattletrap also correctly outputs it as a float.

Rattletrap output:
```                     
"cam_settings": {
                        "angle": -3,
                        "distance": 280,
                        "fov": 110,
                        "height": 110,
                        "stiffness": 0.4,
                        "swivel_speed": 3,
                        "transition_speed": 1.7
                      }
```

I believe the issue is because of https://github.com/SaltieRL/DistributedReplays/blob/0b0add2d13fb12db0612057ca53abdc6cd1a8145/backend/database/objects.py#L112
So in the DB camera transition speed is stored as an integer instead of a float, and sqlalchemy automatically rounds it to the nearest number?

I think if this field gets updated to be a float type, the issue should be resolved (for newer replays?). I've checked the protobufs in the carball project and they do have the right type for transition speed https://github.com/SaltieRL/carball/blob/41d3d56275641aaa4f6b65eb41ba5af35d461830/api/metadata/camera_settings.proto#L9

Example: https://calculated.gg/api/player/76561198374703623/match_history?page=0&limit=1
Yukeo has a transition speed of 1.7 in replays, but the API returns 2.

I'd try to fix it myself but I'm not really well versed in the world of python migrations, and couldn't find out how you guys actually do it (or do it manually?) so I just created this issue instead with the hopes that one of you knew how to properly migrate.

**Comment by dtracers** [comment]
If the Protobufs has the correct speed then we can at least repopulate the database after we fix the column migration.

**Comment by Lyrex** [comment]
I don't really know the project too well, which is why I implemented a (in my view) quite naive fix for the issue. Locally I had no problems (yet?).
Just like bakkes, I'm not too sure if this is all that needs to be done. If so, I'll submit a PR containing the fix.
