### ISSUE TITLE
Math explanation shown as raw LaTeX formula code

### ISSUE THREAD

**Issue by kurisu-gh** [SaltieRL/DistributedReplays#357]
On the [stat explanation page](https://calculated.gg/explanations), I see the raw LaTeX formula instead of the rendered formula. Does anyone else see this? I tried to correct it but when I tested it on my end in a Docker image, it displays correctly albeit after a one or two refreshes of the webpage without any changes to the source.

**Comment by Abbondanzo** [comment]
This issue has been recorded in #225
