### ISSUE TITLE
Total boost efficiency is now (-inf, 0]?

### ISSUE THREAD

**Issue by kurisu-gh** [SaltieRL/DistributedReplays#390]
Total boost efficiency has been redefined to some thing else?
![chrome_tfHWjOhn9P](https://user-images.githubusercontent.com/764773/67119430-1cf2e100-f222-11e9-87a1-f610fc302cba.png)

It's now in the range of what seems to be from some negative number to 0.

**Comment by dtracers** [comment]
There is a bug with boost collection where it said everyone collected zero boost.  This has now been fixed.  So stats should slowly return to normal
