### ISSUE TITLE
Update package.json for replay-viewer 0.5.2 to 0.7.0 breaks application

### ISSUE THREAD

**Issue by krusmir** [SaltieRL/DistributedReplays#430]
Current version of replay-viewer 0.7.0 breaks installation with the following error:

(docker-compose log)
```
webapp_1    | ./node_modules/replay-viewer/loaders/storage/loadBall.js
webapp_1    | Module not found: Can't resolve '../../assets/models/draco/Ball.glb' in '/app/node_modules/replay-viewer/loaders/storage'
```

Reverting to version 0.5.2 fixes this.

Seems the following commit is relevant: https://github.com/SaltieRL/DistributedReplays/commit/01c6e313f9dfa942a15fd284de3e0a08983d8ef3

@dtracers

**Comment by Abbondanzo** [comment]
For now, pull them from https://github.com/SaltieRL/SharedAssets/tree/master/models/draco
This gives me a good excuse to bundle them inside the `replay-viewer` lib now 😄

**Comment by Sciguymjm** [comment]
It also looks like the types change, so the current ReplayViewer.tsx is broken.

**Comment by krusmir** [comment]
@Abbondanzo @Sciguymjm  can confirm.   Just adding models wont work.

**Comment by Abbondanzo** [comment]
Ah yeah, it takes extended players now. I need to make corrections to these. Let's remain on 0.5.2, I'll file a PR
