### ISSUE TITLE
Color switches for players between top graph and other stats

### ISSUE THREAD

**Issue by dbauducco** [SaltieRL/DistributedReplays#70]
The color for players get switched.
Only have looked at doubles.

<img width="548" alt="screen shot 2018-09-16 at 9 14 52 pm" src="https://user-images.githubusercontent.com/32312199/45604018-cea75900-b9f5-11e8-9246-ed1e3ed28173.png">
<img width="305" alt="screen shot 2018-09-16 at 9 14 59 pm" src="https://user-images.githubusercontent.com/32312199/45604019-cea75900-b9f5-11e8-9cd9-019ebcded9b2.png">

**Comment by Sciguymjm** [comment]
This seems to be an issue with sorting of players, since the colors are always in the same order. Hopefully in the rewrite (twoback) this will be consistent.

**Comment by Sciguymjm** [comment]
Rewrite fixes this. Labeling as wontfix
