### ISSUE TITLE
OpenID login fails for steam profile names longer than 10 characters

### ISSUE THREAD

**Issue by kcolton** [SaltieRL/DistributedReplays#9]
Figured out why I was 500ing on steam login. My steam profile/persona name: "AlpacaFlightSim" is longer than the `players.platformname` column which is limited to 10 characters.

```
[SQL: 'INSERT INTO players (platformid, platformname, avatar, ranks) VALUES (%(platformid)s, %(platformname)s, %(avatar)s, %(ranks)s)'] [parameters: {'platformid': '76561197960785799', 'platformname': 'AlpacaFlightSim', 'avatar': 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/d9/d9af01e851ba44a965b178a59447a92228915281_full.jpg', 'ranks': None}]
```

Steam's API docs don't give a specified character limit, the input field for changing the name maxes out at 30.

```
<input class="dynInput" type="text" name="personaName" id="personaName" size="30" value="AlpacaFlightSim">
```

but there's always the possibility of legacy names or who knows. 50 is fine, and we'll be able to monitor once we get sentry setup and all that. No reason to be conservative with varchar sizes. Postgres doesn't care.

PR coming shortly :)

**Comment by Sciguymjm** [comment]
I just now remember that `platformname` was originally supposed to be the platform the player is on, and not their name. However it did not occur to me when I was adding Steam integration. Thanks for taking initiative. 👍
