### ISSUE TITLE
We should inform the user stats are inaccurate when < 10 replays are in the system

### ISSUE THREAD

**Issue by dtracers** [SaltieRL/DistributedReplays#90]

**Comment by twobackfromtheend** [comment]
Solved by #91 
https://cdn.discordapp.com/attachments/471773324549292043/493049097536667648/unknown.png
https://cdn.discordapp.com/attachments/471773324549292043/493049200117022740/unknown.png
[see commit](https://github.com/SaltieRL/DistributedReplays/pull/91/commits/16c7c27b22dc4e019677ed37cc0334cf75afe206)
